# Path: .github/workflows/release.yml
name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - name: Get version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Build binaries
        run: |
          mkdir -p dist
          
          # Linux AMD64
          GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -trimpath \
            -o dist/auditkit-${{ steps.version.outputs.VERSION }}-linux-amd64 ./cmd/auditkit
          
          # Linux ARM64
          GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -trimpath \
            -o dist/auditkit-${{ steps.version.outputs.VERSION }}-linux-arm64 ./cmd/auditkit
          
          # macOS Intel
          GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -trimpath \
            -o dist/auditkit-${{ steps.version.outputs.VERSION }}-darwin-amd64 ./cmd/auditkit
          
          # macOS Apple Silicon
          GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -trimpath \
            -o dist/auditkit-${{ steps.version.outputs.VERSION }}-darwin-arm64 ./cmd/auditkit
          
          # Windows
          GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -trimpath \
            -o dist/auditkit-${{ steps.version.outputs.VERSION }}-windows-amd64.exe ./cmd/auditkit
      
      - name: Create archives
        run: |
          cd dist
          tar -czf auditkit-${{ steps.version.outputs.VERSION }}-linux-amd64.tar.gz auditkit-${{ steps.version.outputs.VERSION }}-linux-amd64
          tar -czf auditkit-${{ steps.version.outputs.VERSION }}-linux-arm64.tar.gz auditkit-${{ steps.version.outputs.VERSION }}-linux-arm64
          tar -czf auditkit-${{ steps.version.outputs.VERSION }}-darwin-amd64.tar.gz auditkit-${{ steps.version.outputs.VERSION }}-darwin-amd64
          tar -czf auditkit-${{ steps.version.outputs.VERSION }}-darwin-arm64.tar.gz auditkit-${{ steps.version.outputs.VERSION }}-darwin-arm64
          zip auditkit-${{ steps.version.outputs.VERSION }}-windows-amd64.zip auditkit-${{ steps.version.outputs.VERSION }}-windows-amd64.exe
          sha256sum *.tar.gz *.zip > checksums.txt
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.tar.gz
            dist/*.zip
            dist/checksums.txt
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
